First commit, ready hw number one
SaveliyLipaev/Homework-2-course pull request #10
Opened 2020-02-16 21:13 UTC by SaveliyLipaev

2020-02-17 10:01 UTC, yurii-litvinov requested changes
Первые три зачтены, последние две предлагаю поправить и заодно написать к ним тесты или хоть что-то, что позволяет убедиться в их работоспособности (например, вызвать из main-а и проверить результат).

2020-02-17 10:01 UTC, yurii-litvinov commented on FirstStepsInF#/FirstStepsInFSharp/FirstStepsInFSharp/Program.fs
> +        countFibonacci 0 1 n
Последовательность Фибоначчи нетрадиционно начинается с нуля

2020-02-17 10:01 UTC, yurii-litvinov commented on FirstStepsInF#/FirstStepsInFSharp/FirstStepsInFSharp/Program.fs
> +            | _ -> doReverse (oldList.Head::newList) (oldList.Tail)
Правильнее было бы шаблоном: `| h::t -> doReverse (h::newList) t`

2020-02-17 10:01 UTC, yurii-litvinov commented on FirstStepsInF#/FirstStepsInFSharp/FirstStepsInFSharp/Program.fs
> +            | _ -> doExponentiationNumberTwo (exp (2) (n + m)::list) (n) (m - 1)
Так надо возводить в степень каждый раз, а можно только один раз.

2020-02-17 10:01 UTC, yurii-litvinov commented on FirstStepsInF#/FirstStepsInFSharp/FirstStepsInFSharp/Program.fs
> +            | [] -> raise (InvalidOperationException())
Отсуствие элемента в списке --- это не исключительная ситуация, тут надо Option возвращать

2020-02-17 10:01 UTC, yurii-litvinov commented on FirstStepsInF#/FirstStepsInFSharp/FirstStepsInFSharp/Program.fs
> +            | _ -> if number = list.Head then index else doGetIndex (number) (index + 1) (list.Tail)
Тут бы тоже шаблон

2020-02-18 07:15 UTC, SaveliyLipaev commented
> Первые три зачтены, последние две предлагаю поправить и заодно написать к ним тесты или хоть что-то, что позволяет убедиться в их работоспособности (например, вызвать из main-а и проверить результат).

А в целом подход такой должен быть? Не уверен что нормально написано

2020-02-18 08:55 UTC, yurii-litvinov approved these changes
Да, вот теперь всё так, но вообще, обычный NUnit в F# тоже работает. Зачтены.

2020-02-18 09:16 UTC, merged