Simple ftp
SaveliyLipaev/Homework-2-course pull request #4
Opened 2019-10-27 23:42 UTC by SaveliyLipaev

2019-10-28 08:15 UTC, yurii-litvinov requested changes
По-хорошему, надо ещё добавить обработку ошибок сети и повтор запросов если что-то пошло не так. Сеть всё-таки принципиально ненадёжна, а текущая реализация чуть что --- сразу падает.

2019-10-28 08:15 UTC, yurii-litvinov commented on SimpleFTP/SimpleFTP/Server.cs
> +                            catch
Нельзя ловить все исключения без разбора

2019-10-28 08:15 UTC, yurii-litvinov commented on SimpleFTP/SimpleFTP/Client.cs
> +        public async Task<string> ListCommand(string path)
От клиента хотелось более высокоуровневого интерфейса --- чтобы он возвращал список каких-то объектов, где хранился бы путь и признак, папка это или файл.

2019-10-28 08:15 UTC, yurii-litvinov commented on SimpleFTP/SimpleFTP/Server.cs
> +                    + string.Join("", directorysName.Select(name => $"{name.Name} True "));
false со строчной, True с заглавной, непорядок

2019-10-29 16:06 UTC, yurii-litvinov requested changes

2019-10-29 16:06 UTC, yurii-litvinov commented on SimpleFTP/SimpleFTP/Client.cs
> +        public bool IsConnect { get; private set; } = false;
Более по-английски `IsConnected`

2019-10-29 16:06 UTC, yurii-litvinov commented on SimpleFTP/SimpleFTP/Client.cs
> +                catch
Нельзя ловить все исключения вообще. Это известный антипаттерн "Error Hiding", так проглатываются исключения, которые могли бы быть ценны для диагностики ошибок. Ловите только те исключения, которых ожидаете

2019-10-29 16:06 UTC, yurii-litvinov commented on SimpleFTP/SimpleFTP/Server.cs
> +    public class Server
С комментариями беда

2019-10-29 16:06 UTC, yurii-litvinov commented on SimpleFTP/SimpleFTPTests/ServerTests.cs
> +            Assert.AreEqual("2 TestFile.txt False TestDir True ", answer.Item1);
От клиента хотелось более высокоуровневого интерфейса --- чтобы он возвращал список каких-то объектов, где хранился бы путь и признак, папка это или файл.

Потому что если писать GUI для такого клиента, то вручную парсить строку неудобно, приятнее получать список объектов, по которому можно ходить.

2019-10-29 16:21 UTC, SaveliyLipaev commented on SimpleFTP/SimpleFTPTests/ServerTests.cs
> +            Assert.AreEqual("2 TestFile.txt False TestDir True ", answer.Item1);
Я и строку возвращаю и список

2019-10-29 23:49 UTC, SaveliyLipaev commented on SimpleFTP/SimpleFTP/Client.cs
> +                catch
Видимо не совсем осознаю концепцию :(

2019-10-31 14:56 UTC, yurii-litvinov requested changes
Почти :)

2019-10-31 14:56 UTC, yurii-litvinov commented on SimpleFTP/SimpleFTPTests/ServerTests.cs
> +            Assert.AreEqual("2 TestFile.txt False TestDir True ", answer.Item1);
А, ага. Тогда можно было бы и строку не возвращать, но, как я понимаю, не хотелось тесты переписывать. Но вдруг список формируется неправильно?

2019-10-31 14:56 UTC, yurii-litvinov commented on SimpleFTP/SimpleFTP/Client.cs
> +            }
Это вообще неправильно.
```csharp
catch 
{
    throw;
}
```
просто ничего не делает

2019-10-31 14:56 UTC, yurii-litvinov commented on SimpleFTP/SimpleFTP/Client.cs
> +                || ex is OutOfMemoryException || ex is ThreadInterruptedException)
Не надо ловить OutOfMemoryException и ThreadInterruptedException, это ж не сетевые ошибки, их никак не исправишь.

2019-10-31 20:11 UTC, yurii-litvinov approved these changes
Окей, зачтена

2019-10-31 20:11 UTC, yurii-litvinov commented on SimpleFTP/SimpleFTP/Client.cs
> +                catch
А тут так и оставили :)

2019-10-31 23:16 UTC, merged